# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FlashLapse_CP.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 670)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 670))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../_image/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Image_Frame = QtWidgets.QLabel(self.centralwidget)
        self.Image_Frame.setGeometry(QtCore.QRect(600, 20, 380, 380))
        self.Image_Frame.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.Image_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Image_Frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Image_Frame.setLineWidth(5)
        self.Image_Frame.setText("")
        self.Image_Frame.setPixmap(QtGui.QPixmap("../_image/Background.png"))
        self.Image_Frame.setScaledContents(True)
        self.Image_Frame.setObjectName("Image_Frame")
        self.Control_Tab = QtWidgets.QTabWidget(self.centralwidget)
        self.Control_Tab.setGeometry(QtCore.QRect(20, 20, 561, 611))
        self.Control_Tab.setTabPosition(QtWidgets.QTabWidget.North)
        self.Control_Tab.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.Control_Tab.setObjectName("Control_Tab")
        self.lighting_tab = QtWidgets.QWidget()
        self.lighting_tab.setObjectName("lighting_tab")
        self.frame_2 = QtWidgets.QFrame(self.lighting_tab)
        self.frame_2.setGeometry(QtCore.QRect(390, 20, 141, 531))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.frame_2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 380, 121, 121))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.powerCycle_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.powerCycle_label.setObjectName("powerCycle_label")
        self.verticalLayout_5.addWidget(self.powerCycle_label)
        self.Cycle_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.Cycle_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Cycle_label.setObjectName("Cycle_label")
        self.verticalLayout_5.addWidget(self.Cycle_label)
        self.powerCycle_spinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        self.powerCycle_spinBox.setMinimum(1)
        self.powerCycle_spinBox.setMaximum(999999999)
        self.powerCycle_spinBox.setProperty("value", 60)
        self.powerCycle_spinBox.setObjectName("powerCycle_spinBox")
        self.verticalLayout_5.addWidget(self.powerCycle_spinBox)
        self.confirmCycle_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.confirmCycle_pushButton.setObjectName("confirmCycle_pushButton")
        self.verticalLayout_5.addWidget(self.confirmCycle_pushButton)
        self.Modes_label = QtWidgets.QLabel(self.frame_2)
        self.Modes_label.setGeometry(QtCore.QRect(10, 20, 121, 29))
        self.Modes_label.setObjectName("Modes_label")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.frame_2)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(20, 50, 111, 301))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.disco_spinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget_3)
        self.disco_spinBox.setMaximum(1000)
        self.disco_spinBox.setObjectName("disco_spinBox")
        self.verticalLayout_3.addWidget(self.disco_spinBox)
        self.disco_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.disco_pushButton.setEnabled(True)
        self.disco_pushButton.setObjectName("disco_pushButton")
        self.verticalLayout_3.addWidget(self.disco_pushButton)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.rainbow_spinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget_3)
        self.rainbow_spinBox.setMaximum(1000)
        self.rainbow_spinBox.setObjectName("rainbow_spinBox")
        self.verticalLayout_3.addWidget(self.rainbow_spinBox)
        self.rainbow_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.rainbow_pushButton.setEnabled(True)
        self.rainbow_pushButton.setObjectName("rainbow_pushButton")
        self.verticalLayout_3.addWidget(self.rainbow_pushButton)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.pulse_spinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget_3)
        self.pulse_spinBox.setMaximum(999999)
        self.pulse_spinBox.setObjectName("pulse_spinBox")
        self.verticalLayout_3.addWidget(self.pulse_spinBox)
        self.pulse_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pulse_pushButton.setEnabled(True)
        self.pulse_pushButton.setObjectName("pulse_pushButton")
        self.verticalLayout_3.addWidget(self.pulse_pushButton)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.sundial_spinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget_3)
        self.sundial_spinBox.setMinimum(1)
        self.sundial_spinBox.setMaximum(999)
        self.sundial_spinBox.setObjectName("sundial_spinBox")
        self.verticalLayout_3.addWidget(self.sundial_spinBox)
        self.sundial_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.sundial_pushButton.setEnabled(True)
        self.sundial_pushButton.setObjectName("sundial_pushButton")
        self.verticalLayout_3.addWidget(self.sundial_pushButton)
        self.image_frame = QtWidgets.QFrame(self.lighting_tab)
        self.image_frame.setGeometry(QtCore.QRect(20, 20, 361, 341))
        self.image_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.image_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.image_frame.setObjectName("image_frame")
        self.coreImage = QtWidgets.QLabel(self.image_frame)
        self.coreImage.setGeometry(QtCore.QRect(30, 20, 300, 300))
        self.coreImage.setText("")
        self.coreImage.setPixmap(QtGui.QPixmap("../_image/graphics.png"))
        self.coreImage.setScaledContents(True)
        self.coreImage.setObjectName("coreImage")
        self.Ligting_frame = QtWidgets.QFrame(self.lighting_tab)
        self.Ligting_frame.setGeometry(QtCore.QRect(20, 370, 361, 181))
        self.Ligting_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.Ligting_frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Ligting_frame.setObjectName("Ligting_frame")
        self.Address_label = QtWidgets.QLabel(self.Ligting_frame)
        self.Address_label.setGeometry(QtCore.QRect(110, 0, 141, 31))
        self.Address_label.setObjectName("Address_label")
        self.color_label = QtWidgets.QLabel(self.Ligting_frame)
        self.color_label.setGeometry(QtCore.QRect(110, 65, 141, 31))
        self.color_label.setObjectName("color_label")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.Ligting_frame)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(20, 19, 321, 51))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.Start_label = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.Start_label.setObjectName("Start_label")
        self.verticalLayout_18.addWidget(self.Start_label)
        self.Start_spinBox = QtWidgets.QSpinBox(self.horizontalLayoutWidget_4)
        self.Start_spinBox.setMaximum(58)
        self.Start_spinBox.setObjectName("Start_spinBox")
        self.verticalLayout_18.addWidget(self.Start_spinBox)
        self.horizontalLayout_5.addLayout(self.verticalLayout_18)
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.End_label = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.End_label.setObjectName("End_label")
        self.verticalLayout_19.addWidget(self.End_label)
        self.End_spinBox = QtWidgets.QSpinBox(self.horizontalLayoutWidget_4)
        self.End_spinBox.setMinimum(1)
        self.End_spinBox.setMaximum(58)
        self.End_spinBox.setProperty("value", 58)
        self.End_spinBox.setObjectName("End_spinBox")
        self.verticalLayout_19.addWidget(self.End_spinBox)
        self.horizontalLayout_5.addLayout(self.verticalLayout_19)
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.BRT_lable = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.BRT_lable.setAlignment(QtCore.Qt.AlignCenter)
        self.BRT_lable.setObjectName("BRT_lable")
        self.verticalLayout_20.addWidget(self.BRT_lable)
        self.BRT_spinBox = QtWidgets.QSpinBox(self.horizontalLayoutWidget_4)
        self.BRT_spinBox.setMinimum(1)
        self.BRT_spinBox.setMaximum(100)
        self.BRT_spinBox.setProperty("value", 20)
        self.BRT_spinBox.setObjectName("BRT_spinBox")
        self.verticalLayout_20.addWidget(self.BRT_spinBox)
        self.horizontalLayout_5.addLayout(self.verticalLayout_20)
        self.gridLayoutWidget = QtWidgets.QWidget(self.Ligting_frame)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 90, 331, 41))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.G_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.G_label.setObjectName("G_label")
        self.gridLayout.addWidget(self.G_label, 0, 2, 1, 1)
        self.R_spinBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.R_spinBox.setMaximum(100)
        self.R_spinBox.setObjectName("R_spinBox")
        self.gridLayout.addWidget(self.R_spinBox, 0, 1, 1, 1)
        self.G_spinBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.G_spinBox.setMaximum(100)
        self.G_spinBox.setObjectName("G_spinBox")
        self.gridLayout.addWidget(self.G_spinBox, 0, 3, 1, 1)
        self.R_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.R_label.setObjectName("R_label")
        self.gridLayout.addWidget(self.R_label, 0, 0, 1, 1)
        self.B_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.B_label.setObjectName("B_label")
        self.gridLayout.addWidget(self.B_label, 0, 4, 1, 1)
        self.B_spinBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B_spinBox.setMaximum(100)
        self.B_spinBox.setObjectName("B_spinBox")
        self.gridLayout.addWidget(self.B_spinBox, 0, 5, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.Ligting_frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(89, 130, 171, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lightConfirm_pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.lightConfirm_pushButton.setObjectName("lightConfirm_pushButton")
        self.horizontalLayout.addWidget(self.lightConfirm_pushButton)
        self.lightReset_pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.lightReset_pushButton.setObjectName("lightReset_pushButton")
        self.horizontalLayout.addWidget(self.lightReset_pushButton)
        self.Control_Tab.addTab(self.lighting_tab, "")
        self.motion_tab = QtWidgets.QWidget()
        self.motion_tab.setObjectName("motion_tab")
        self.motion_tabWidget = QtWidgets.QTabWidget(self.motion_tab)
        self.motion_tabWidget.setGeometry(QtCore.QRect(20, 20, 511, 501))
        self.motion_tabWidget.setObjectName("motion_tabWidget")
        self.scheduler_tab = QtWidgets.QWidget()
        self.scheduler_tab.setObjectName("scheduler_tab")
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.scheduler_tab)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(205, 15, 81, 51))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.rotate1_label = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.rotate1_label.setAlignment(QtCore.Qt.AlignCenter)
        self.rotate1_label.setObjectName("rotate1_label")
        self.verticalLayout_11.addWidget(self.rotate1_label)
        self.rotate1_spinbox = QtWidgets.QSpinBox(self.verticalLayoutWidget_6)
        self.rotate1_spinbox.setMinimum(-180)
        self.rotate1_spinbox.setMaximum(180)
        self.rotate1_spinbox.setProperty("value", 10)
        self.rotate1_spinbox.setObjectName("rotate1_spinbox")
        self.verticalLayout_11.addWidget(self.rotate1_spinbox)
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.scheduler_tab)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(325, 115, 81, 51))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.wait1_label = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.wait1_label.setAlignment(QtCore.Qt.AlignCenter)
        self.wait1_label.setObjectName("wait1_label")
        self.verticalLayout_14.addWidget(self.wait1_label)
        self.wait1_spinbox = QtWidgets.QSpinBox(self.verticalLayoutWidget_7)
        self.wait1_spinbox.setMinimum(1)
        self.wait1_spinbox.setMaximum(1440)
        self.wait1_spinbox.setObjectName("wait1_spinbox")
        self.verticalLayout_14.addWidget(self.wait1_spinbox)
        self.graphic_2 = QtWidgets.QLabel(self.scheduler_tab)
        self.graphic_2.setGeometry(QtCore.QRect(170, 70, 150, 150))
        self.graphic_2.setText("")
        self.graphic_2.setPixmap(QtGui.QPixmap("../_image/Scheduler.png"))
        self.graphic_2.setScaledContents(True)
        self.graphic_2.setObjectName("graphic_2")
        self.R1 = QtWidgets.QLabel(self.scheduler_tab)
        self.R1.setGeometry(QtCore.QRect(315, 35, 71, 71))
        self.R1.setText("")
        self.R1.setPixmap(QtGui.QPixmap("../_image/R1.png"))
        self.R1.setScaledContents(True)
        self.R1.setObjectName("R1")
        self.verticalLayoutWidget_9 = QtWidgets.QWidget(self.scheduler_tab)
        self.verticalLayoutWidget_9.setGeometry(QtCore.QRect(85, 115, 81, 51))
        self.verticalLayoutWidget_9.setObjectName("verticalLayoutWidget_9")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_9)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.wait2_label = QtWidgets.QLabel(self.verticalLayoutWidget_9)
        self.wait2_label.setAlignment(QtCore.Qt.AlignCenter)
        self.wait2_label.setObjectName("wait2_label")
        self.verticalLayout_16.addWidget(self.wait2_label)
        self.wait2_spinbox = QtWidgets.QSpinBox(self.verticalLayoutWidget_9)
        self.wait2_spinbox.setMinimum(1)
        self.wait2_spinbox.setMaximum(1440)
        self.wait2_spinbox.setObjectName("wait2_spinbox")
        self.verticalLayout_16.addWidget(self.wait2_spinbox)
        self.line_2 = QtWidgets.QFrame(self.scheduler_tab)
        self.line_2.setGeometry(QtCore.QRect(20, 290, 461, 21))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.R3 = QtWidgets.QLabel(self.scheduler_tab)
        self.R3.setGeometry(QtCore.QRect(105, 175, 71, 71))
        self.R3.setText("")
        self.R3.setPixmap(QtGui.QPixmap("../_image/L2.png"))
        self.R3.setScaledContents(True)
        self.R3.setObjectName("R3")
        self.verticalLayoutWidget_8 = QtWidgets.QWidget(self.scheduler_tab)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(205, 235, 81, 51))
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_8)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.rotate2_label = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.rotate2_label.setAlignment(QtCore.Qt.AlignCenter)
        self.rotate2_label.setObjectName("rotate2_label")
        self.verticalLayout_15.addWidget(self.rotate2_label)
        self.rotate2_spinbox = QtWidgets.QSpinBox(self.verticalLayoutWidget_8)
        self.rotate2_spinbox.setMinimum(-180)
        self.rotate2_spinbox.setMaximum(180)
        self.rotate2_spinbox.setProperty("value", -10)
        self.rotate2_spinbox.setObjectName("rotate2_spinbox")
        self.verticalLayout_15.addWidget(self.rotate2_spinbox)
        self.R2 = QtWidgets.QLabel(self.scheduler_tab)
        self.R2.setGeometry(QtCore.QRect(315, 175, 71, 71))
        self.R2.setText("")
        self.R2.setPixmap(QtGui.QPixmap("../_image/R2.png"))
        self.R2.setScaledContents(True)
        self.R2.setObjectName("R2")
        self.R4 = QtWidgets.QLabel(self.scheduler_tab)
        self.R4.setGeometry(QtCore.QRect(105, 35, 71, 71))
        self.R4.setText("")
        self.R4.setPixmap(QtGui.QPixmap("../_image/L1.png"))
        self.R4.setScaledContents(True)
        self.R4.setObjectName("R4")
        self.verticalLayoutWidget_10 = QtWidgets.QWidget(self.scheduler_tab)
        self.verticalLayoutWidget_10.setGeometry(QtCore.QRect(30, 330, 441, 132))
        self.verticalLayoutWidget_10.setObjectName("verticalLayoutWidget_10")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_10)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.schedulerTest_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_10)
        self.schedulerTest_pushButton.setCheckable(False)
        self.schedulerTest_pushButton.setChecked(False)
        self.schedulerTest_pushButton.setObjectName("schedulerTest_pushButton")
        self.verticalLayout_17.addWidget(self.schedulerTest_pushButton)
        self.schedulerSet_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_10)
        self.schedulerSet_pushButton.setObjectName("schedulerSet_pushButton")
        self.verticalLayout_17.addWidget(self.schedulerSet_pushButton)
        self.motion_tabWidget.addTab(self.scheduler_tab, "")
        self.clinostat_tab = QtWidgets.QWidget()
        self.clinostat_tab.setObjectName("clinostat_tab")
        self.R4_2 = QtWidgets.QLabel(self.clinostat_tab)
        self.R4_2.setGeometry(QtCore.QRect(105, 35, 71, 71))
        self.R4_2.setText("")
        self.R4_2.setPixmap(QtGui.QPixmap("../_image/L1.png"))
        self.R4_2.setScaledContents(True)
        self.R4_2.setObjectName("R4_2")
        self.R1_2 = QtWidgets.QLabel(self.clinostat_tab)
        self.R1_2.setGeometry(QtCore.QRect(315, 35, 71, 71))
        self.R1_2.setText("")
        self.R1_2.setPixmap(QtGui.QPixmap("../_image/R1.png"))
        self.R1_2.setScaledContents(True)
        self.R1_2.setObjectName("R1_2")
        self.graphic_3 = QtWidgets.QLabel(self.clinostat_tab)
        self.graphic_3.setGeometry(QtCore.QRect(170, 70, 150, 150))
        self.graphic_3.setText("")
        self.graphic_3.setPixmap(QtGui.QPixmap("../_image/Scheduler.png"))
        self.graphic_3.setScaledContents(True)
        self.graphic_3.setObjectName("graphic_3")
        self.R3_2 = QtWidgets.QLabel(self.clinostat_tab)
        self.R3_2.setGeometry(QtCore.QRect(105, 175, 71, 71))
        self.R3_2.setText("")
        self.R3_2.setPixmap(QtGui.QPixmap("../_image/L2.png"))
        self.R3_2.setScaledContents(True)
        self.R3_2.setObjectName("R3_2")
        self.R2_2 = QtWidgets.QLabel(self.clinostat_tab)
        self.R2_2.setGeometry(QtCore.QRect(315, 175, 71, 71))
        self.R2_2.setText("")
        self.R2_2.setPixmap(QtGui.QPixmap("../_image/R2.png"))
        self.R2_2.setScaledContents(True)
        self.R2_2.setObjectName("R2_2")
        self.line_4 = QtWidgets.QFrame(self.clinostat_tab)
        self.line_4.setGeometry(QtCore.QRect(20, 290, 461, 21))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayoutWidget_12 = QtWidgets.QWidget(self.clinostat_tab)
        self.verticalLayoutWidget_12.setGeometry(QtCore.QRect(30, 330, 441, 132))
        self.verticalLayoutWidget_12.setObjectName("verticalLayoutWidget_12")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_12)
        self.verticalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.clinostatSet_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_12)
        self.clinostatSet_pushButton.setObjectName("clinostatSet_pushButton")
        self.verticalLayout_21.addWidget(self.clinostatSet_pushButton)
        self.motion_tabWidget.addTab(self.clinostat_tab, "")
        self.motorSpeed_label = QtWidgets.QLabel(self.motion_tab)
        self.motorSpeed_label.setGeometry(QtCore.QRect(430, 530, 121, 31))
        self.motorSpeed_label.setObjectName("motorSpeed_label")
        self.motorSpeed_slider = QtWidgets.QSlider(self.motion_tab)
        self.motorSpeed_slider.setGeometry(QtCore.QRect(28, 530, 381, 32))
        self.motorSpeed_slider.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.motorSpeed_slider.setMinimum(10)
        self.motorSpeed_slider.setMaximum(100)
        self.motorSpeed_slider.setSingleStep(1)
        self.motorSpeed_slider.setPageStep(30)
        self.motorSpeed_slider.setProperty("value", 50)
        self.motorSpeed_slider.setSliderPosition(50)
        self.motorSpeed_slider.setOrientation(QtCore.Qt.Horizontal)
        self.motorSpeed_slider.setInvertedControls(True)
        self.motorSpeed_slider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.motorSpeed_slider.setTickInterval(5)
        self.motorSpeed_slider.setObjectName("motorSpeed_slider")
        self.Control_Tab.addTab(self.motion_tab, "")
        self.imaging_tab = QtWidgets.QWidget()
        self.imaging_tab.setObjectName("imaging_tab")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.imaging_tab)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(20, 420, 281, 54))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.x_label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.x_label.setObjectName("x_label")
        self.gridLayout_2.addWidget(self.x_label, 0, 1, 1, 1)
        self.x_resolution_spinBox = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.x_resolution_spinBox.setMinimum(50)
        self.x_resolution_spinBox.setMaximum(3240)
        self.x_resolution_spinBox.setProperty("value", 2464)
        self.x_resolution_spinBox.setObjectName("x_resolution_spinBox")
        self.gridLayout_2.addWidget(self.x_resolution_spinBox, 0, 0, 1, 1)
        self.y_resolution_spinBox = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.y_resolution_spinBox.setMinimum(50)
        self.y_resolution_spinBox.setMaximum(2464)
        self.y_resolution_spinBox.setProperty("value", 2464)
        self.y_resolution_spinBox.setObjectName("y_resolution_spinBox")
        self.gridLayout_2.addWidget(self.y_resolution_spinBox, 0, 2, 1, 1)
        self.xRange_label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.xRange_label.setAlignment(QtCore.Qt.AlignCenter)
        self.xRange_label.setObjectName("xRange_label")
        self.gridLayout_2.addWidget(self.xRange_label, 1, 0, 1, 1)
        self.CoreCtr_label_6 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.CoreCtr_label_6.setObjectName("CoreCtr_label_6")
        self.gridLayout_2.addWidget(self.CoreCtr_label_6, 1, 1, 1, 1)
        self.yRange_label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.yRange_label.setAlignment(QtCore.Qt.AlignCenter)
        self.yRange_label.setObjectName("yRange_label")
        self.gridLayout_2.addWidget(self.yRange_label, 1, 2, 1, 1)
        self.resolution_label = QtWidgets.QLabel(self.imaging_tab)
        self.resolution_label.setGeometry(QtCore.QRect(45, 390, 231, 31))
        self.resolution_label.setObjectName("resolution_label")
        self.format_label = QtWidgets.QLabel(self.imaging_tab)
        self.format_label.setGeometry(QtCore.QRect(310, 390, 231, 31))
        self.format_label.setObjectName("format_label")
        self.layoutWidget = QtWidgets.QWidget(self.imaging_tab)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 500, 511, 61))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.Progress_Label = QtWidgets.QLabel(self.layoutWidget)
        self.Progress_Label.setObjectName("Progress_Label")
        self.verticalLayout_7.addWidget(self.Progress_Label, 0, QtCore.Qt.AlignHCenter)
        self.Progress_Bar = QtWidgets.QProgressBar(self.layoutWidget)
        self.Progress_Bar.setEnabled(False)
        self.Progress_Bar.setProperty("value", 0)
        self.Progress_Bar.setObjectName("Progress_Bar")
        self.verticalLayout_7.addWidget(self.Progress_Bar)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.imaging_tab)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(330, 420, 201, 51))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.JPG_radioButton = QtWidgets.QRadioButton(self.horizontalLayoutWidget_6)
        self.JPG_radioButton.setChecked(True)
        self.JPG_radioButton.setObjectName("JPG_radioButton")
        self.horizontalLayout_7.addWidget(self.JPG_radioButton)
        self.PNG_radioButton = QtWidgets.QRadioButton(self.horizontalLayoutWidget_6)
        self.PNG_radioButton.setObjectName("PNG_radioButton")
        self.horizontalLayout_7.addWidget(self.PNG_radioButton)
        self.storage_tabWidget = QtWidgets.QTabWidget(self.imaging_tab)
        self.storage_tabWidget.setGeometry(QtCore.QRect(20, 260, 521, 131))
        self.storage_tabWidget.setObjectName("storage_tabWidget")
        self.local_tab = QtWidgets.QWidget()
        self.local_tab.setObjectName("local_tab")
        self.verticalLayoutWidget_13 = QtWidgets.QWidget(self.local_tab)
        self.verticalLayoutWidget_13.setGeometry(QtCore.QRect(19, 11, 461, 81))
        self.verticalLayoutWidget_13.setObjectName("verticalLayoutWidget_13")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_13)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem4)
        self.directory_label = QtWidgets.QLabel(self.verticalLayoutWidget_13)
        self.directory_label.setEnabled(True)
        self.directory_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.directory_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.directory_label.setAlignment(QtCore.Qt.AlignCenter)
        self.directory_label.setObjectName("directory_label")
        self.verticalLayout_9.addWidget(self.directory_label)
        self.directory_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_13)
        self.directory_pushButton.setEnabled(True)
        self.directory_pushButton.setCheckable(False)
        self.directory_pushButton.setObjectName("directory_pushButton")
        self.verticalLayout_9.addWidget(self.directory_pushButton)
        self.storage_tabWidget.addTab(self.local_tab, "")
        self.cloud_tab = QtWidgets.QWidget()
        self.cloud_tab.setObjectName("cloud_tab")
        self.verticalLayoutWidget_14 = QtWidgets.QWidget(self.cloud_tab)
        self.verticalLayoutWidget_14.setGeometry(QtCore.QRect(20, 10, 491, 84))
        self.verticalLayoutWidget_14.setObjectName("verticalLayoutWidget_14")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_14)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem5)
        self.Email_label = QtWidgets.QLabel(self.verticalLayoutWidget_14)
        self.Email_label.setObjectName("Email_label")
        self.verticalLayout_10.addWidget(self.Email_label)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Email_lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_14)
        self.Email_lineEdit.setObjectName("Email_lineEdit")
        self.horizontalLayout_4.addWidget(self.Email_lineEdit)
        self.emailDefault_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_14)
        self.emailDefault_pushButton.setEnabled(True)
        self.emailDefault_pushButton.setObjectName("emailDefault_pushButton")
        self.horizontalLayout_4.addWidget(self.emailDefault_pushButton)
        self.verticalLayout_10.addLayout(self.horizontalLayout_4)
        self.emailConfirm_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_14)
        self.emailConfirm_pushButton.setEnabled(True)
        self.emailConfirm_pushButton.setObjectName("emailConfirm_pushButton")
        self.verticalLayout_10.addWidget(self.emailConfirm_pushButton)
        self.storage_tabWidget.addTab(self.cloud_tab, "")
        self.layoutWidget1 = QtWidgets.QWidget(self.imaging_tab)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 20, 509, 221))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.imageTitle_label = QtWidgets.QLabel(self.layoutWidget1)
        self.imageTitle_label.setObjectName("imageTitle_label")
        self.verticalLayout.addWidget(self.imageTitle_label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.imageTitle_lineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.imageTitle_lineEdit.setEnabled(True)
        self.imageTitle_lineEdit.setObjectName("imageTitle_lineEdit")
        self.horizontalLayout_2.addWidget(self.imageTitle_lineEdit)
        self.addDate_pushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.addDate_pushButton.setEnabled(False)
        self.addDate_pushButton.setObjectName("addDate_pushButton")
        self.horizontalLayout_2.addWidget(self.addDate_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem6 = QtWidgets.QSpacerItem(20, 38, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.ImageInterval_label = QtWidgets.QLabel(self.layoutWidget1)
        self.ImageInterval_label.setObjectName("ImageInterval_label")
        self.verticalLayout.addWidget(self.ImageInterval_label)
        self.ImageInterval_spinBox = QtWidgets.QSpinBox(self.layoutWidget1)
        self.ImageInterval_spinBox.setEnabled(True)
        self.ImageInterval_spinBox.setMinimum(1)
        self.ImageInterval_spinBox.setMaximum(99999999)
        self.ImageInterval_spinBox.setObjectName("ImageInterval_spinBox")
        self.verticalLayout.addWidget(self.ImageInterval_spinBox)
        spacerItem7 = QtWidgets.QSpacerItem(20, 38, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem7)
        self.imageDuration_label = QtWidgets.QLabel(self.layoutWidget1)
        self.imageDuration_label.setObjectName("imageDuration_label")
        self.verticalLayout.addWidget(self.imageDuration_label)
        self.imageDuration_spinBox = QtWidgets.QSpinBox(self.layoutWidget1)
        self.imageDuration_spinBox.setEnabled(True)
        self.imageDuration_spinBox.setMinimum(1)
        self.imageDuration_spinBox.setMaximum(99999999)
        self.imageDuration_spinBox.setObjectName("imageDuration_spinBox")
        self.verticalLayout.addWidget(self.imageDuration_spinBox)
        self.line = QtWidgets.QFrame(self.imaging_tab)
        self.line.setGeometry(QtCore.QRect(40, 480, 471, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.Control_Tab.addTab(self.imaging_tab, "")
        self.Misc_Frame = QtWidgets.QFrame(self.centralwidget)
        self.Misc_Frame.setGeometry(QtCore.QRect(600, 410, 381, 221))
        self.Misc_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Misc_Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Misc_Frame.setObjectName("Misc_Frame")
        self.verticalLayoutWidget_15 = QtWidgets.QWidget(self.Misc_Frame)
        self.verticalLayoutWidget_15.setGeometry(QtCore.QRect(10, 130, 131, 80))
        self.verticalLayoutWidget_15.setObjectName("verticalLayoutWidget_15")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_15)
        self.verticalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.motor_label = QtWidgets.QLabel(self.verticalLayoutWidget_15)
        self.motor_label.setObjectName("motor_label")
        self.verticalLayout_22.addWidget(self.motor_label)
        self.motor_spinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget_15)
        self.motor_spinBox.setObjectName("motor_spinBox")
        self.verticalLayout_22.addWidget(self.motor_spinBox)
        self.motorConfirm_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_15)
        self.motorConfirm_pushButton.setObjectName("motorConfirm_pushButton")
        self.verticalLayout_22.addWidget(self.motorConfirm_pushButton)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.Misc_Frame)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(240, 10, 136, 114))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.snapshot_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.snapshot_pushButton.setEnabled(True)
        self.snapshot_pushButton.setObjectName("snapshot_pushButton")
        self.verticalLayout_13.addWidget(self.snapshot_pushButton)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.liveFeed_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.liveFeed_pushButton.setObjectName("liveFeed_pushButton")
        self.horizontalLayout_6.addWidget(self.liveFeed_pushButton)
        self.liveFeed_spinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget_5)
        self.liveFeed_spinBox.setMinimum(1)
        self.liveFeed_spinBox.setMaximum(600)
        self.liveFeed_spinBox.setObjectName("liveFeed_spinBox")
        self.horizontalLayout_6.addWidget(self.liveFeed_spinBox)
        self.verticalLayout_13.addLayout(self.horizontalLayout_6)
        self.preview_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.preview_pushButton.setEnabled(True)
        self.preview_pushButton.setObjectName("preview_pushButton")
        self.verticalLayout_13.addWidget(self.preview_pushButton)
        self.rotate_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.rotate_pushButton.setObjectName("rotate_pushButton")
        self.verticalLayout_13.addWidget(self.rotate_pushButton)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.Misc_Frame)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(13, 10, 211, 111))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.AOI_label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.AOI_label_3.setObjectName("AOI_label_3")
        self.verticalLayout_12.addWidget(self.AOI_label_3)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.AOIX_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_4)
        self.AOIX_doubleSpinBox.setMaximum(1.0)
        self.AOIX_doubleSpinBox.setSingleStep(0.1)
        self.AOIX_doubleSpinBox.setObjectName("AOIX_doubleSpinBox")
        self.gridLayout_3.addWidget(self.AOIX_doubleSpinBox, 2, 0, 1, 1)
        self.AOIW_label = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.AOIW_label.setObjectName("AOIW_label")
        self.gridLayout_3.addWidget(self.AOIW_label, 1, 2, 1, 1)
        self.AOIW_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_4)
        self.AOIW_doubleSpinBox.setMaximum(1.0)
        self.AOIW_doubleSpinBox.setSingleStep(0.1)
        self.AOIW_doubleSpinBox.setProperty("value", 1.0)
        self.AOIW_doubleSpinBox.setObjectName("AOIW_doubleSpinBox")
        self.gridLayout_3.addWidget(self.AOIW_doubleSpinBox, 2, 2, 1, 1)
        self.AOIH_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_4)
        self.AOIH_doubleSpinBox.setMaximum(1.0)
        self.AOIH_doubleSpinBox.setSingleStep(0.1)
        self.AOIH_doubleSpinBox.setProperty("value", 1.0)
        self.AOIH_doubleSpinBox.setObjectName("AOIH_doubleSpinBox")
        self.gridLayout_3.addWidget(self.AOIH_doubleSpinBox, 2, 3, 1, 1)
        self.AOIX_label = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.AOIX_label.setObjectName("AOIX_label")
        self.gridLayout_3.addWidget(self.AOIX_label, 1, 0, 1, 1)
        self.AOIY_label = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.AOIY_label.setObjectName("AOIY_label")
        self.gridLayout_3.addWidget(self.AOIY_label, 1, 1, 1, 1)
        self.AOIY_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_4)
        self.AOIY_doubleSpinBox.setMaximum(1.0)
        self.AOIY_doubleSpinBox.setSingleStep(0.1)
        self.AOIY_doubleSpinBox.setObjectName("AOIY_doubleSpinBox")
        self.gridLayout_3.addWidget(self.AOIY_doubleSpinBox, 2, 1, 1, 1)
        self.AOIH_label = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.AOIH_label.setObjectName("AOIH_label")
        self.gridLayout_3.addWidget(self.AOIH_label, 1, 3, 1, 1)
        self.verticalLayout_12.addLayout(self.gridLayout_3)
        self.AOI_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.AOI_pushButton.setEnabled(True)
        self.AOI_pushButton.setObjectName("AOI_pushButton")
        self.verticalLayout_12.addWidget(self.AOI_pushButton)
        self.startRoutines_pushButton = QtWidgets.QPushButton(self.Misc_Frame)
        self.startRoutines_pushButton.setGeometry(QtCore.QRect(160, 150, 211, 61))
        self.startRoutines_pushButton.setObjectName("startRoutines_pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionOpen_Directory = QtWidgets.QAction(MainWindow)
        self.actionOpen_Directory.setEnabled(False)
        self.actionOpen_Directory.setObjectName("actionOpen_Directory")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionCreate_Timelapse = QtWidgets.QAction(MainWindow)
        self.actionCreate_Timelapse.setObjectName("actionCreate_Timelapse")

        self.retranslateUi(MainWindow)
        self.Control_Tab.setCurrentIndex(2)
        self.motion_tabWidget.setCurrentIndex(0)
        self.storage_tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FlashLapse Commad Point"))
        self.powerCycle_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Power Cycle</span></p></body></html>"))
        self.Cycle_label.setText(_translate("MainWindow", "Cycle Duration:"))
        self.powerCycle_spinBox.setSuffix(_translate("MainWindow", " min"))
        self.confirmCycle_pushButton.setText(_translate("MainWindow", "CONFIRM"))
        self.Modes_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Modes</span></p></body></html>"))
        self.disco_spinBox.setSuffix(_translate("MainWindow", " ms"))
        self.disco_pushButton.setText(_translate("MainWindow", "Disco"))
        self.rainbow_spinBox.setSuffix(_translate("MainWindow", " ms"))
        self.rainbow_pushButton.setText(_translate("MainWindow", "Rainbow"))
        self.pulse_spinBox.setSuffix(_translate("MainWindow", " ms"))
        self.pulse_pushButton.setText(_translate("MainWindow", "Pluse"))
        self.sundial_spinBox.setSuffix(_translate("MainWindow", " s"))
        self.sundial_pushButton.setText(_translate("MainWindow", "Sundial"))
        self.Address_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">LED Address</span></p></body></html>"))
        self.color_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Color Setting</span></p></body></html>"))
        self.Start_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Start LED:</span></p></body></html>"))
        self.Start_spinBox.setPrefix(_translate("MainWindow", "# "))
        self.End_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">End LED:</span></p></body></html>"))
        self.End_spinBox.setPrefix(_translate("MainWindow", "# "))
        self.BRT_lable.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Brightness:</span></p></body></html>"))
        self.BRT_spinBox.setSuffix(_translate("MainWindow", " %"))
        self.G_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Green:</span></p></body></html>"))
        self.R_spinBox.setSuffix(_translate("MainWindow", " %"))
        self.G_spinBox.setSuffix(_translate("MainWindow", " %"))
        self.R_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Red:</span></p></body></html>"))
        self.B_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Blue:</span></p></body></html>"))
        self.B_spinBox.setSuffix(_translate("MainWindow", " %"))
        self.lightConfirm_pushButton.setText(_translate("MainWindow", "CONFIRM"))
        self.lightReset_pushButton.setText(_translate("MainWindow", "RESET"))
        self.Control_Tab.setTabText(self.Control_Tab.indexOf(self.lighting_tab), _translate("MainWindow", "Lighting"))
        self.rotate1_label.setText(_translate("MainWindow", "Reflex To"))
        self.rotate1_spinbox.setSuffix(_translate("MainWindow", " °"))
        self.wait1_label.setText(_translate("MainWindow", "Pause For"))
        self.wait1_spinbox.setSuffix(_translate("MainWindow", " min"))
        self.wait2_label.setText(_translate("MainWindow", "Pause For"))
        self.wait2_spinbox.setSuffix(_translate("MainWindow", " min"))
        self.rotate2_label.setText(_translate("MainWindow", "Reflex To"))
        self.rotate2_spinbox.setSuffix(_translate("MainWindow", " °"))
        self.schedulerTest_pushButton.setText(_translate("MainWindow", "Test Run"))
        self.schedulerSet_pushButton.setText(_translate("MainWindow", "Set Schedule"))
        self.motion_tabWidget.setTabText(self.motion_tabWidget.indexOf(self.scheduler_tab), _translate("MainWindow", "Scheduler"))
        self.clinostatSet_pushButton.setText(_translate("MainWindow", "Set Clinostat"))
        self.motion_tabWidget.setTabText(self.motion_tabWidget.indexOf(self.clinostat_tab), _translate("MainWindow", "Clinostat"))
        self.motorSpeed_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Motor RPM: 5.0</p></body></html>"))
        self.Control_Tab.setTabText(self.Control_Tab.indexOf(self.motion_tab), _translate("MainWindow", "Motion"))
        self.x_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">X</p></body></html>"))
        self.x_resolution_spinBox.setSuffix(_translate("MainWindow", " px"))
        self.y_resolution_spinBox.setSuffix(_translate("MainWindow", " px"))
        self.xRange_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#000000;\">[ 50 , 3240 ]</span></p></body></html>"))
        self.CoreCtr_label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.yRange_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#000000;\">[ 50 , 2464 ]</span></p></body></html>"))
        self.resolution_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">IMAGING RESOLUTION</span></p></body></html>"))
        self.format_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">IMAGE FORMAT</span></p></body></html>"))
        self.Progress_Label.setText(_translate("MainWindow", "Progress: 0 / 1"))
        self.JPG_radioButton.setText(_translate("MainWindow", ".JPG"))
        self.PNG_radioButton.setText(_translate("MainWindow", ".PNG"))
        self.directory_label.setText(_translate("MainWindow", "Sequence Title Required"))
        self.directory_pushButton.setText(_translate("MainWindow", "Select Storage Directory"))
        self.storage_tabWidget.setTabText(self.storage_tabWidget.indexOf(self.local_tab), _translate("MainWindow", "Local"))
        self.Email_label.setText(_translate("MainWindow", "Please Enter Your Email Adress: "))
        self.emailDefault_pushButton.setText(_translate("MainWindow", "Save default"))
        self.emailConfirm_pushButton.setText(_translate("MainWindow", "Confirm Email"))
        self.storage_tabWidget.setTabText(self.storage_tabWidget.indexOf(self.cloud_tab), _translate("MainWindow", "Cloud"))
        self.imageTitle_label.setText(_translate("MainWindow", "Image Sequence Title"))
        self.addDate_pushButton.setText(_translate("MainWindow", "Add Date"))
        self.ImageInterval_label.setText(_translate("MainWindow", "Image Capture Interval"))
        self.ImageInterval_spinBox.setSuffix(_translate("MainWindow", " min"))
        self.imageDuration_label.setText(_translate("MainWindow", "Image Sequence Duration"))
        self.imageDuration_spinBox.setSuffix(_translate("MainWindow", " min"))
        self.Control_Tab.setTabText(self.Control_Tab.indexOf(self.imaging_tab), _translate("MainWindow", "Imaging"))
        self.motor_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Rotate Motor</span></p></body></html>"))
        self.motor_spinBox.setSuffix(_translate("MainWindow", " °"))
        self.motorConfirm_pushButton.setText(_translate("MainWindow", "Start Routines"))
        self.snapshot_pushButton.setText(_translate("MainWindow", "Snapshot"))
        self.liveFeed_pushButton.setText(_translate("MainWindow", "Live Feed"))
        self.liveFeed_spinBox.setSuffix(_translate("MainWindow", " s"))
        self.preview_pushButton.setText(_translate("MainWindow", "Full Preview"))
        self.rotate_pushButton.setText(_translate("MainWindow", "Rotate Image"))
        self.AOI_label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">AREA OF INTEREST</span></p></body></html>"))
        self.AOIW_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">W</span></p></body></html>"))
        self.AOIX_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">X</span></p></body></html>"))
        self.AOIY_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Y</span></p></body></html>"))
        self.AOIH_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">H</span></p></body></html>"))
        self.AOI_pushButton.setText(_translate("MainWindow", "Confirm"))
        self.startRoutines_pushButton.setText(_translate("MainWindow", "Start Routines"))
        self.actionOpen_Directory.setText(_translate("MainWindow", "Open Directory"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionCreate_Timelapse.setText(_translate("MainWindow", "Create Timelapse"))


