# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FlashLapse_CP.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 670)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../_image/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Image_Frame = QtWidgets.QLabel(self.centralwidget)
        self.Image_Frame.setGeometry(QtCore.QRect(620, 20, 350, 350))
        self.Image_Frame.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.Image_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Image_Frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Image_Frame.setLineWidth(5)
        self.Image_Frame.setText("")
        self.Image_Frame.setPixmap(QtGui.QPixmap("../_image/Background.png"))
        self.Image_Frame.setScaledContents(True)
        self.Image_Frame.setObjectName("Image_Frame")
        self.Control_Tab = QtWidgets.QTabWidget(self.centralwidget)
        self.Control_Tab.setGeometry(QtCore.QRect(20, 20, 561, 601))
        self.Control_Tab.setTabPosition(QtWidgets.QTabWidget.North)
        self.Control_Tab.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.Control_Tab.setObjectName("Control_Tab")
        self.Lighting = QtWidgets.QWidget()
        self.Lighting.setObjectName("Lighting")
        self.frame_2 = QtWidgets.QFrame(self.Lighting)
        self.frame_2.setGeometry(QtCore.QRect(390, 20, 141, 531))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.frame_2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 380, 121, 121))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lightCycle_label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.lightCycle_label_2.setObjectName("lightCycle_label_2")
        self.verticalLayout_5.addWidget(self.lightCycle_label_2)
        self.Cycle_label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.Cycle_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Cycle_label_2.setObjectName("Cycle_label_2")
        self.verticalLayout_5.addWidget(self.Cycle_label_2)
        self.powerCycle_spinBox_2 = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        self.powerCycle_spinBox_2.setMinimum(1)
        self.powerCycle_spinBox_2.setMaximum(999999999)
        self.powerCycle_spinBox_2.setProperty("value", 60)
        self.powerCycle_spinBox_2.setObjectName("powerCycle_spinBox_2")
        self.verticalLayout_5.addWidget(self.powerCycle_spinBox_2)
        self.confirmCycle_pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.confirmCycle_pushButton_2.setObjectName("confirmCycle_pushButton_2")
        self.verticalLayout_5.addWidget(self.confirmCycle_pushButton_2)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.frame_2)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 50, 121, 91))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.disco_pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.disco_pushButton_2.setEnabled(False)
        self.disco_pushButton_2.setObjectName("disco_pushButton_2")
        self.verticalLayout_6.addWidget(self.disco_pushButton_2)
        self.rainbow_pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.rainbow_pushButton_2.setEnabled(False)
        self.rainbow_pushButton_2.setObjectName("rainbow_pushButton_2")
        self.verticalLayout_6.addWidget(self.rainbow_pushButton_2)
        self.lightCycle_label_3 = QtWidgets.QLabel(self.frame_2)
        self.lightCycle_label_3.setGeometry(QtCore.QRect(10, 20, 119, 29))
        self.lightCycle_label_3.setObjectName("lightCycle_label_3")
        self.frame = QtWidgets.QFrame(self.Lighting)
        self.frame.setGeometry(QtCore.QRect(20, 20, 361, 341))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.coreImage = QtWidgets.QLabel(self.frame)
        self.coreImage.setGeometry(QtCore.QRect(30, 20, 300, 300))
        self.coreImage.setText("")
        self.coreImage.setPixmap(QtGui.QPixmap("../_image/graphics.png"))
        self.coreImage.setScaledContents(True)
        self.coreImage.setObjectName("coreImage")
        self.frame_5 = QtWidgets.QFrame(self.Lighting)
        self.frame_5.setGeometry(QtCore.QRect(20, 370, 361, 181))
        self.frame_5.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_5.setObjectName("frame_5")
        self.Address_label = QtWidgets.QLabel(self.frame_5)
        self.Address_label.setGeometry(QtCore.QRect(110, 0, 141, 31))
        self.Address_label.setObjectName("Address_label")
        self.color_label = QtWidgets.QLabel(self.frame_5)
        self.color_label.setGeometry(QtCore.QRect(110, 65, 141, 31))
        self.color_label.setObjectName("color_label")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.frame_5)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(20, 19, 321, 51))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.Start_label = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.Start_label.setObjectName("Start_label")
        self.verticalLayout_18.addWidget(self.Start_label)
        self.Start_spinBox = QtWidgets.QSpinBox(self.horizontalLayoutWidget_4)
        self.Start_spinBox.setMaximum(33)
        self.Start_spinBox.setObjectName("Start_spinBox")
        self.verticalLayout_18.addWidget(self.Start_spinBox)
        self.horizontalLayout_5.addLayout(self.verticalLayout_18)
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.Start_label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.Start_label_3.setObjectName("Start_label_3")
        self.verticalLayout_19.addWidget(self.Start_label_3)
        self.End_spinBox = QtWidgets.QSpinBox(self.horizontalLayoutWidget_4)
        self.End_spinBox.setMinimum(1)
        self.End_spinBox.setMaximum(34)
        self.End_spinBox.setObjectName("End_spinBox")
        self.verticalLayout_19.addWidget(self.End_spinBox)
        self.horizontalLayout_5.addLayout(self.verticalLayout_19)
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.BRT_lable = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.BRT_lable.setObjectName("BRT_lable")
        self.verticalLayout_20.addWidget(self.BRT_lable)
        self.BRT_spinBox = QtWidgets.QSpinBox(self.horizontalLayoutWidget_4)
        self.BRT_spinBox.setMinimum(1)
        self.BRT_spinBox.setMaximum(255)
        self.BRT_spinBox.setProperty("value", 50)
        self.BRT_spinBox.setObjectName("BRT_spinBox")
        self.verticalLayout_20.addWidget(self.BRT_spinBox)
        self.horizontalLayout_5.addLayout(self.verticalLayout_20)
        self.gridLayoutWidget = QtWidgets.QWidget(self.frame_5)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 90, 331, 71))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.B_spinBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B_spinBox.setMaximum(255)
        self.B_spinBox.setObjectName("B_spinBox")
        self.gridLayout.addWidget(self.B_spinBox, 1, 1, 1, 1)
        self.W_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.W_label.setObjectName("W_label")
        self.gridLayout.addWidget(self.W_label, 1, 2, 1, 1)
        self.R_spinBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.R_spinBox.setMaximum(255)
        self.R_spinBox.setObjectName("R_spinBox")
        self.gridLayout.addWidget(self.R_spinBox, 0, 1, 1, 1)
        self.W_spinBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.W_spinBox.setMaximum(255)
        self.W_spinBox.setObjectName("W_spinBox")
        self.gridLayout.addWidget(self.W_spinBox, 1, 3, 1, 1)
        self.G_spinBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.G_spinBox.setMaximum(255)
        self.G_spinBox.setObjectName("G_spinBox")
        self.gridLayout.addWidget(self.G_spinBox, 0, 3, 1, 1)
        self.light_Reset_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.light_Reset_pushButton.setObjectName("light_Reset_pushButton")
        self.gridLayout.addWidget(self.light_Reset_pushButton, 0, 4, 1, 1)
        self.light_Confirm_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.light_Confirm_pushButton.setObjectName("light_Confirm_pushButton")
        self.gridLayout.addWidget(self.light_Confirm_pushButton, 1, 4, 1, 1)
        self.G_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.G_label.setObjectName("G_label")
        self.gridLayout.addWidget(self.G_label, 0, 2, 1, 1)
        self.R_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.R_label.setObjectName("R_label")
        self.gridLayout.addWidget(self.R_label, 0, 0, 1, 1)
        self.B_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.B_label.setObjectName("B_label")
        self.gridLayout.addWidget(self.B_label, 1, 0, 1, 1)
        self.Control_Tab.addTab(self.Lighting, "")
        self.Imaging = QtWidgets.QWidget()
        self.Imaging.setObjectName("Imaging")
        self.layoutWidget_2 = QtWidgets.QWidget(self.Imaging)
        self.layoutWidget_2.setGeometry(QtCore.QRect(20, 20, 511, 331))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.Image_Title = QtWidgets.QLabel(self.layoutWidget_2)
        self.Image_Title.setObjectName("Image_Title")
        self.verticalLayout.addWidget(self.Image_Title)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.title_lineEdit = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.title_lineEdit.setEnabled(True)
        self.title_lineEdit.setObjectName("title_lineEdit")
        self.horizontalLayout_2.addWidget(self.title_lineEdit)
        self.addDate_pushButton = QtWidgets.QPushButton(self.layoutWidget_2)
        self.addDate_pushButton.setEnabled(False)
        self.addDate_pushButton.setObjectName("addDate_pushButton")
        self.horizontalLayout_2.addWidget(self.addDate_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 38, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.Image_Interval = QtWidgets.QLabel(self.layoutWidget_2)
        self.Image_Interval.setObjectName("Image_Interval")
        self.verticalLayout.addWidget(self.Image_Interval)
        self.ICI_spinBox = QtWidgets.QSpinBox(self.layoutWidget_2)
        self.ICI_spinBox.setEnabled(True)
        self.ICI_spinBox.setMinimum(1)
        self.ICI_spinBox.setMaximum(99999999)
        self.ICI_spinBox.setObjectName("ICI_spinBox")
        self.verticalLayout.addWidget(self.ICI_spinBox)
        spacerItem1 = QtWidgets.QSpacerItem(20, 38, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Image_Duration = QtWidgets.QLabel(self.layoutWidget_2)
        self.Image_Duration.setObjectName("Image_Duration")
        self.verticalLayout_2.addWidget(self.Image_Duration)
        self.ISD_spinBox = QtWidgets.QSpinBox(self.layoutWidget_2)
        self.ISD_spinBox.setEnabled(True)
        self.ISD_spinBox.setMinimum(1)
        self.ISD_spinBox.setMaximum(99999999)
        self.ISD_spinBox.setObjectName("ISD_spinBox")
        self.verticalLayout_2.addWidget(self.ISD_spinBox)
        self.line_3 = QtWidgets.QFrame(self.layoutWidget_2)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_2.addWidget(self.line_3)
        spacerItem2 = QtWidgets.QSpacerItem(20, 120, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.directory_label = QtWidgets.QLabel(self.layoutWidget_2)
        self.directory_label.setEnabled(True)
        self.directory_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.directory_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.directory_label.setAlignment(QtCore.Qt.AlignCenter)
        self.directory_label.setObjectName("directory_label")
        self.verticalLayout_2.addWidget(self.directory_label)
        self.directory_pushButton = QtWidgets.QPushButton(self.layoutWidget_2)
        self.directory_pushButton.setEnabled(True)
        self.directory_pushButton.setCheckable(False)
        self.directory_pushButton.setObjectName("directory_pushButton")
        self.verticalLayout_2.addWidget(self.directory_pushButton)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.Imaging)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(20, 410, 281, 54))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.CoreCtr_label_5 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.CoreCtr_label_5.setObjectName("CoreCtr_label_5")
        self.gridLayout_2.addWidget(self.CoreCtr_label_5, 0, 1, 1, 1)
        self.x_resolution_spinBox = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.x_resolution_spinBox.setMinimum(50)
        self.x_resolution_spinBox.setMaximum(3240)
        self.x_resolution_spinBox.setProperty("value", 2464)
        self.x_resolution_spinBox.setObjectName("x_resolution_spinBox")
        self.gridLayout_2.addWidget(self.x_resolution_spinBox, 0, 0, 1, 1)
        self.y_resolution_spinBox = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.y_resolution_spinBox.setMinimum(50)
        self.y_resolution_spinBox.setMaximum(2464)
        self.y_resolution_spinBox.setProperty("value", 2464)
        self.y_resolution_spinBox.setObjectName("y_resolution_spinBox")
        self.gridLayout_2.addWidget(self.y_resolution_spinBox, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.CoreCtr_label_6 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.CoreCtr_label_6.setObjectName("CoreCtr_label_6")
        self.gridLayout_2.addWidget(self.CoreCtr_label_6, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 2, 1, 1)
        self.resolution_label = QtWidgets.QLabel(self.Imaging)
        self.resolution_label.setGeometry(QtCore.QRect(45, 380, 231, 31))
        self.resolution_label.setObjectName("resolution_label")
        self.resolution_label_2 = QtWidgets.QLabel(self.Imaging)
        self.resolution_label_2.setGeometry(QtCore.QRect(310, 380, 231, 31))
        self.resolution_label_2.setObjectName("resolution_label_2")
        self.layoutWidget = QtWidgets.QWidget(self.Imaging)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 500, 511, 61))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.Progress_Label = QtWidgets.QLabel(self.layoutWidget)
        self.Progress_Label.setObjectName("Progress_Label")
        self.verticalLayout_7.addWidget(self.Progress_Label, 0, QtCore.Qt.AlignHCenter)
        self.Progress_Bar = QtWidgets.QProgressBar(self.layoutWidget)
        self.Progress_Bar.setEnabled(False)
        self.Progress_Bar.setProperty("value", 0)
        self.Progress_Bar.setObjectName("Progress_Bar")
        self.verticalLayout_7.addWidget(self.Progress_Bar)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.Imaging)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(330, 410, 201, 51))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.JPG_radioButton = QtWidgets.QRadioButton(self.horizontalLayoutWidget_6)
        self.JPG_radioButton.setChecked(True)
        self.JPG_radioButton.setObjectName("JPG_radioButton")
        self.horizontalLayout_7.addWidget(self.JPG_radioButton)
        self.PNG_radioButton = QtWidgets.QRadioButton(self.horizontalLayoutWidget_6)
        self.PNG_radioButton.setObjectName("PNG_radioButton")
        self.horizontalLayout_7.addWidget(self.PNG_radioButton)
        self.Control_Tab.addTab(self.Imaging, "")
        self.Motion = QtWidgets.QWidget()
        self.Motion.setObjectName("Motion")
        self.tabWidget = QtWidgets.QTabWidget(self.Motion)
        self.tabWidget.setGeometry(QtCore.QRect(20, 20, 511, 531))
        self.tabWidget.setObjectName("tabWidget")
        self.Scheduler = QtWidgets.QWidget()
        self.Scheduler.setObjectName("Scheduler")
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.Scheduler)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(205, 15, 81, 51))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.Rotate1 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.Rotate1.setAlignment(QtCore.Qt.AlignCenter)
        self.Rotate1.setObjectName("Rotate1")
        self.verticalLayout_11.addWidget(self.Rotate1)
        self.rotate_to_spinbox_1 = QtWidgets.QSpinBox(self.verticalLayoutWidget_6)
        self.rotate_to_spinbox_1.setMinimum(-180)
        self.rotate_to_spinbox_1.setMaximum(180)
        self.rotate_to_spinbox_1.setObjectName("rotate_to_spinbox_1")
        self.verticalLayout_11.addWidget(self.rotate_to_spinbox_1)
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.Scheduler)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(325, 115, 81, 51))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.Wait1 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.Wait1.setAlignment(QtCore.Qt.AlignCenter)
        self.Wait1.setObjectName("Wait1")
        self.verticalLayout_14.addWidget(self.Wait1)
        self.wait_spinbox_1 = QtWidgets.QSpinBox(self.verticalLayoutWidget_7)
        self.wait_spinbox_1.setMinimum(1)
        self.wait_spinbox_1.setMaximum(1440)
        self.wait_spinbox_1.setObjectName("wait_spinbox_1")
        self.verticalLayout_14.addWidget(self.wait_spinbox_1)
        self.Color_Frame_2 = QtWidgets.QLabel(self.Scheduler)
        self.Color_Frame_2.setGeometry(QtCore.QRect(170, 70, 150, 150))
        self.Color_Frame_2.setText("")
        self.Color_Frame_2.setPixmap(QtGui.QPixmap("../_image/Scheduler.png"))
        self.Color_Frame_2.setScaledContents(True)
        self.Color_Frame_2.setObjectName("Color_Frame_2")
        self.R1 = QtWidgets.QLabel(self.Scheduler)
        self.R1.setGeometry(QtCore.QRect(315, 35, 71, 71))
        self.R1.setText("")
        self.R1.setPixmap(QtGui.QPixmap("../_image/R1.png"))
        self.R1.setScaledContents(True)
        self.R1.setObjectName("R1")
        self.verticalLayoutWidget_9 = QtWidgets.QWidget(self.Scheduler)
        self.verticalLayoutWidget_9.setGeometry(QtCore.QRect(85, 115, 81, 51))
        self.verticalLayoutWidget_9.setObjectName("verticalLayoutWidget_9")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_9)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.Wait2 = QtWidgets.QLabel(self.verticalLayoutWidget_9)
        self.Wait2.setAlignment(QtCore.Qt.AlignCenter)
        self.Wait2.setObjectName("Wait2")
        self.verticalLayout_16.addWidget(self.Wait2)
        self.wait_spinbox_2 = QtWidgets.QSpinBox(self.verticalLayoutWidget_9)
        self.wait_spinbox_2.setMinimum(1)
        self.wait_spinbox_2.setMaximum(1440)
        self.wait_spinbox_2.setObjectName("wait_spinbox_2")
        self.verticalLayout_16.addWidget(self.wait_spinbox_2)
        self.line_2 = QtWidgets.QFrame(self.Scheduler)
        self.line_2.setGeometry(QtCore.QRect(-50, 285, 551, 21))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.R2_2 = QtWidgets.QLabel(self.Scheduler)
        self.R2_2.setGeometry(QtCore.QRect(105, 175, 71, 71))
        self.R2_2.setText("")
        self.R2_2.setPixmap(QtGui.QPixmap("../_image/L2.png"))
        self.R2_2.setScaledContents(True)
        self.R2_2.setObjectName("R2_2")
        self.verticalLayoutWidget_8 = QtWidgets.QWidget(self.Scheduler)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(205, 235, 81, 51))
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_8)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.Rotate2 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.Rotate2.setAlignment(QtCore.Qt.AlignCenter)
        self.Rotate2.setObjectName("Rotate2")
        self.verticalLayout_15.addWidget(self.Rotate2)
        self.rotate_to_spinbox_2 = QtWidgets.QSpinBox(self.verticalLayoutWidget_8)
        self.rotate_to_spinbox_2.setMinimum(-180)
        self.rotate_to_spinbox_2.setMaximum(180)
        self.rotate_to_spinbox_2.setObjectName("rotate_to_spinbox_2")
        self.verticalLayout_15.addWidget(self.rotate_to_spinbox_2)
        self.R2 = QtWidgets.QLabel(self.Scheduler)
        self.R2.setGeometry(QtCore.QRect(315, 175, 71, 71))
        self.R2.setText("")
        self.R2.setPixmap(QtGui.QPixmap("../_image/R2.png"))
        self.R2.setScaledContents(True)
        self.R2.setObjectName("R2")
        self.R2_3 = QtWidgets.QLabel(self.Scheduler)
        self.R2_3.setGeometry(QtCore.QRect(105, 35, 71, 71))
        self.R2_3.setText("")
        self.R2_3.setPixmap(QtGui.QPixmap("../_image/L1.png"))
        self.R2_3.setScaledContents(True)
        self.R2_3.setObjectName("R2_3")
        self.Speed_Select = QtWidgets.QSlider(self.Scheduler)
        self.Speed_Select.setGeometry(QtCore.QRect(50, 340, 271, 21))
        self.Speed_Select.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.Speed_Select.setMinimum(100)
        self.Speed_Select.setMaximum(1000)
        self.Speed_Select.setSingleStep(20)
        self.Speed_Select.setPageStep(30)
        self.Speed_Select.setProperty("value", 600)
        self.Speed_Select.setSliderPosition(600)
        self.Speed_Select.setOrientation(QtCore.Qt.Horizontal)
        self.Speed_Select.setInvertedControls(True)
        self.Speed_Select.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.Speed_Select.setTickInterval(50)
        self.Speed_Select.setObjectName("Speed_Select")
        self.verticalLayoutWidget_10 = QtWidgets.QWidget(self.Scheduler)
        self.verticalLayoutWidget_10.setGeometry(QtCore.QRect(340, 330, 131, 132))
        self.verticalLayoutWidget_10.setObjectName("verticalLayoutWidget_10")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_10)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.Reset_Position = QtWidgets.QPushButton(self.verticalLayoutWidget_10)
        self.Reset_Position.setObjectName("Reset_Position")
        self.verticalLayout_17.addWidget(self.Reset_Position)
        self.Test_Run = QtWidgets.QPushButton(self.verticalLayoutWidget_10)
        self.Test_Run.setCheckable(False)
        self.Test_Run.setChecked(False)
        self.Test_Run.setObjectName("Test_Run")
        self.verticalLayout_17.addWidget(self.Test_Run)
        self.Set_Schedule = QtWidgets.QPushButton(self.verticalLayoutWidget_10)
        self.Set_Schedule.setObjectName("Set_Schedule")
        self.verticalLayout_17.addWidget(self.Set_Schedule)
        self.Motor_Speed = QtWidgets.QLabel(self.Scheduler)
        self.Motor_Speed.setGeometry(QtCore.QRect(50, 360, 139, 21))
        self.Motor_Speed.setObjectName("Motor_Speed")
        self.Total_Reflex = QtWidgets.QSpinBox(self.Scheduler)
        self.Total_Reflex.setGeometry(QtCore.QRect(220, 390, 101, 22))
        self.Total_Reflex.setMaximum(99999)
        self.Total_Reflex.setObjectName("Total_Reflex")
        self.label_10 = QtWidgets.QLabel(self.Scheduler)
        self.label_10.setGeometry(QtCore.QRect(50, 390, 161, 21))
        self.label_10.setObjectName("label_10")
        self.tabWidget.addTab(self.Scheduler, "")
        self.Clinostat = QtWidgets.QWidget()
        self.Clinostat.setObjectName("Clinostat")
        self.tabWidget.addTab(self.Clinostat, "")
        self.Control_Tab.addTab(self.Motion, "")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(620, 390, 211, 61))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.Local_Storage = QtWidgets.QRadioButton(self.verticalLayoutWidget_4)
        self.Local_Storage.setChecked(True)
        self.Local_Storage.setObjectName("Local_Storage")
        self.verticalLayout_12.addWidget(self.Local_Storage)
        self.Cloud_Sync = QtWidgets.QRadioButton(self.verticalLayoutWidget_4)
        self.Cloud_Sync.setEnabled(False)
        self.Cloud_Sync.setObjectName("Cloud_Sync")
        self.verticalLayout_12.addWidget(self.Cloud_Sync)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(840, 380, 141, 111))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.Snapshot = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.Snapshot.setEnabled(True)
        self.Snapshot.setObjectName("Snapshot")
        self.verticalLayout_13.addWidget(self.Snapshot)
        self.Live_Feed = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.Live_Feed.setObjectName("Live_Feed")
        self.verticalLayout_13.addWidget(self.Live_Feed)
        self.Rotate = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.Rotate.setObjectName("Rotate")
        self.verticalLayout_13.addWidget(self.Rotate)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(760, 510, 221, 81))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionOpen_Directory = QtWidgets.QAction(MainWindow)
        self.actionOpen_Directory.setEnabled(False)
        self.actionOpen_Directory.setObjectName("actionOpen_Directory")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionCreate_Timelapse = QtWidgets.QAction(MainWindow)
        self.actionCreate_Timelapse.setObjectName("actionCreate_Timelapse")

        self.retranslateUi(MainWindow)
        self.Control_Tab.setCurrentIndex(2)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FlashLapse Commad Point"))
        self.lightCycle_label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Power Cycle</span></p></body></html>"))
        self.Cycle_label_2.setText(_translate("MainWindow", "Cycle Duration:"))
        self.powerCycle_spinBox_2.setSuffix(_translate("MainWindow", " min"))
        self.confirmCycle_pushButton_2.setText(_translate("MainWindow", "CONFIRM"))
        self.disco_pushButton_2.setText(_translate("MainWindow", "Disco"))
        self.rainbow_pushButton_2.setText(_translate("MainWindow", "Rainbow"))
        self.lightCycle_label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Presets</span></p></body></html>"))
        self.Address_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">LED Address</span></p></body></html>"))
        self.color_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Color Setting</span></p></body></html>"))
        self.Start_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Start LED:</span></p></body></html>"))
        self.Start_label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">End LED:</span></p></body></html>"))
        self.BRT_lable.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Brightness:</span></p></body></html>"))
        self.W_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">White:</span></p></body></html>"))
        self.light_Reset_pushButton.setText(_translate("MainWindow", "RESET"))
        self.light_Confirm_pushButton.setText(_translate("MainWindow", "CONFIRM"))
        self.G_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Green:</span></p></body></html>"))
        self.R_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Red:</span></p></body></html>"))
        self.B_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Blue:</span></p></body></html>"))
        self.Control_Tab.setTabText(self.Control_Tab.indexOf(self.Lighting), _translate("MainWindow", "Lighting"))
        self.Image_Title.setText(_translate("MainWindow", "Image Sequence Title"))
        self.addDate_pushButton.setText(_translate("MainWindow", "Add Date"))
        self.Image_Interval.setText(_translate("MainWindow", "Image Capture Interval"))
        self.ICI_spinBox.setSuffix(_translate("MainWindow", " min"))
        self.Image_Duration.setText(_translate("MainWindow", "Image Sequence Duration"))
        self.ISD_spinBox.setSuffix(_translate("MainWindow", " min"))
        self.directory_label.setText(_translate("MainWindow", "Sequence Title Required"))
        self.directory_pushButton.setText(_translate("MainWindow", "Select Storage Directory"))
        self.CoreCtr_label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">X</p></body></html>"))
        self.x_resolution_spinBox.setSuffix(_translate("MainWindow", " px"))
        self.y_resolution_spinBox.setSuffix(_translate("MainWindow", " px"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#000000;\">[ 50 , 3240 ]</span></p></body></html>"))
        self.CoreCtr_label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#000000;\">[ 50 , 2464 ]</span></p></body></html>"))
        self.resolution_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">IMAGING RESOLUTION</span></p></body></html>"))
        self.resolution_label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">IMAGE FORMAT</span></p></body></html>"))
        self.Progress_Label.setText(_translate("MainWindow", "Progress: 0 / 1"))
        self.JPG_radioButton.setText(_translate("MainWindow", ".JPG"))
        self.PNG_radioButton.setText(_translate("MainWindow", ".PNG"))
        self.Control_Tab.setTabText(self.Control_Tab.indexOf(self.Imaging), _translate("MainWindow", "Settings"))
        self.Rotate1.setText(_translate("MainWindow", "Reflex To"))
        self.rotate_to_spinbox_1.setSuffix(_translate("MainWindow", " °"))
        self.Wait1.setText(_translate("MainWindow", "Pause For"))
        self.wait_spinbox_1.setSuffix(_translate("MainWindow", " min"))
        self.Wait2.setText(_translate("MainWindow", "Pause For"))
        self.wait_spinbox_2.setSuffix(_translate("MainWindow", " min"))
        self.Rotate2.setText(_translate("MainWindow", "Reflex To"))
        self.rotate_to_spinbox_2.setSuffix(_translate("MainWindow", " °"))
        self.Reset_Position.setText(_translate("MainWindow", "Reset Position"))
        self.Test_Run.setText(_translate("MainWindow", "Test Run"))
        self.Set_Schedule.setText(_translate("MainWindow", "Set Schedule"))
        self.Motor_Speed.setText(_translate("MainWindow", "Motor Speed: 600"))
        self.Total_Reflex.setSuffix(_translate("MainWindow", " RFLX"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Experiment Duration:</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Scheduler), _translate("MainWindow", "Scheduler"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Clinostat), _translate("MainWindow", "Clinostat"))
        self.Control_Tab.setTabText(self.Control_Tab.indexOf(self.Motion), _translate("MainWindow", "Motion"))
        self.Local_Storage.setText(_translate("MainWindow", "Local Storage"))
        self.Cloud_Sync.setText(_translate("MainWindow", "Cloud Sync"))
        self.Snapshot.setText(_translate("MainWindow", "Snapshot"))
        self.Live_Feed.setText(_translate("MainWindow", "Live Feed (30s)"))
        self.Rotate.setText(_translate("MainWindow", "Rotate Image"))
        self.pushButton.setText(_translate("MainWindow", "Start Scheduled Imaging"))
        self.actionOpen_Directory.setText(_translate("MainWindow", "Open Directory"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionCreate_Timelapse.setText(_translate("MainWindow", "Create Timelapse"))


